/* **********************************************************************
Copyright 2020  Dr. J. C. Shillcock and Prof. Dr. R. Lipowsky, Director at the Max Planck Institute (MPI) of Colloids and Interfaces; Head of Department Theory and Bio-Systems.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
********************************************************************** */
// prFormin.cpp: implementation of the prFormin class.
//
//////////////////////////////////////////////////////////////////////

#include "StdAfx.h"
#include "SimDefs.h"
#include "SimMathFlags.h"
#include "SimAlgorithmFlags.h"
#include "SimXMLFlags.h"
#include "prFormin.h"
#include "LogCreateEventFailed.h"
#include "SimState.h"
#include "ISimBox.h"
#include "TimeSeriesData.h"
#include "InputData.h"
#include "aaRegionToType.h"
#include "Slice.h"

// Active Cell Network monitored by the process

#include "aeForminNetwork.h"

// Commands generated by the process

// Commands implementing the IModifyBLMVesicleFusion interface

#include "pcBLMVesicleFusionSetCondenseDelay.h"

// Messages issued as a result of process logic

#include "LogCommandFailed.h"
#include "LogpcBLMVesicleFusionSetCondenseDelay.h"


// STL using declarations


//////////////////////////////////////////////////////////////////////
// Global members
//////////////////////////////////////////////////////////////////////

// Static member variable containing the identifier for this process. 
// The static member function GetType() is invoked by the xxProcessObject 
// to compare the type read from the control data file with each
// xxProcess-derived class so that it can create the appropriate object 
// to hold the process data.
//
// NOTE. For processes attached to ACNs this identifier must be IDENTICAL to
// that in the associated ACN class. We cannot use a call to 
// aefActinNetwork::GetType() to access the ACN's static member because not
// all compilers will initialise the ACN before this class.
	
const zString prFormin::m_Type = "Formin";

const zString prFormin::GetType()
{
	return m_Type;
}

// We use an anonymous namespace to wrap the call to the factory object
// so that it is not accessible from outside this file. The identifying
// string is stored in the m_Type static member variable.
//
// Note that the Create() function is not a member function but a global 
// function hidden in the namespace.

namespace
{
	xxProcess* Create() {return new prFormin();}

	const zString id = prFormin::GetType();

	const bool bRegistered = acfProcessFactory::Instance()->Register(id, Create);
}

//////////////////////////////////////////////////////////////////////
// Construction/Destruction
//////////////////////////////////////////////////////////////////////

// Constructor for use when the acfProcessFactory class creates a process
// according to its string identifier read from the control data file.

prFormin::prFormin() : IModifyForminProcess(),
                        m_pACN(0), m_bIsModifiable(false), m_bNeverModifiable(false), 
						m_MonomerTotal(0),
						m_FreeMonomerTotal(0), m_BoundMonomerTotal(0), m_FilamentTotal(0),
						m_FreeMonomerFraction(0.0), m_BoundMonomerFraction(0.0),
						m_MeanFilamentSize(0.0),
						m_SDevFilamentSize(0.0),
						m_MeanFilamentLength(0.0),
						m_SDevFilamentLength(0.0)
{
}

// Constructor for use by the shadow SimBox so that it can attach the process
// to the ACN allowing it to serialise its data. This constructor cannot be called
// by the acfProcessFactory class and should only be used internally.

prFormin::prFormin(const aeForminNetwork* pACN, long start, long end) : m_pACN(pACN),
											m_bIsModifiable(true), m_bNeverModifiable(false), 
											m_MonomerTotal(0),
											m_FreeMonomerTotal(0), m_BoundMonomerTotal(0), m_FilamentTotal(0),
											m_FreeMonomerFraction(0.0), m_BoundMonomerFraction(0.0),
											m_MeanFilamentSize(0.0),
											m_SDevFilamentSize(0.0),
											m_MeanFilamentLength(0.0),
											m_SDevFilamentLength(0.0)
{
	// Now that the base class part of this class has been constructed, set the
	// time interval for process analysis. This is for informational purposes
	// in the process state's file only, as the times are not used in the analysis.

	SetStartTime(start);
	SetEndTime(end);
}

prFormin::~prFormin()
{

}

// Member functions to write/read the data specific to the process.
// The put() function is empty as the base class putASCIIStartTags(), 
// putASCIIEndTags() and their XML equivalents replace its function.

zOutStream& prFormin::put(zOutStream& os) const
{
	return os;
}

zInStream& prFormin::get(zInStream& is)
{
	// Read base class data first

	xxProcess::get(is);

	// No data entry required for this process as it is internal

	return is;
}


// Non-static function to return the type of the process

const zString prFormin::GetProcessType() const
{
	// We return the associated ACN's type so that the ACN and process
	// are guaranteed to return the same string

	return aeForminNetwork::GetType();
}

// Function to return a pointer to a copy of the current process.

xxProcess* prFormin::GetProcess() const
{
	return new prFormin(*this);
}

// Function to update the state of the process using data from the associated
// aggregates (CVesicle) and events (evVesiclePore,...).
//
// This process monitors the aeForminNetwork and outputs analysis of the filament
// growth.
//

void prFormin::UpdateState(CSimState& rSimState, const ISimBox* const pISimBox)
{
	// Obtain the filament analysis data to be output to the process file: 

	m_FreeMonomerTotal		= m_pACN->GetFreeBondTotal();
	m_BoundMonomerTotal		= m_pACN->GetBoundBondTotal();
	m_FreeMonomerFraction	= m_pACN->GetFreeBondFraction();
	m_BoundMonomerFraction	= m_pACN->GetBoundBondFraction();
	m_FilamentTotal			= m_pACN->GetFilamentTotal();
	m_MeanFilamentSize		= m_pACN->GetMeanFilamentSize();
	m_SDevFilamentSize		= m_pACN->GetSDevFilamentSize();
	m_MeanFilamentLength	= m_pACN->GetMeanFilamentLength();
	m_SDevFilamentLength	= m_pACN->GetSDevFilamentLength();

	long dataTotal = 10;

	CTimeSeriesData* const pTSD = new CTimeSeriesData(dataTotal);

	pTSD->SetValue(0, pISimBox->GetCurrentTime(), "Time");
	pTSD->SetValue(1, m_FreeMonomerTotal,		"FreeMonomerTotal");
	pTSD->SetValue(2, m_BoundMonomerTotal,		"BoundMonomerTotal");
	pTSD->SetValue(3, m_FreeMonomerFraction,	"FreeMonomerFraction");
	pTSD->SetValue(4, m_BoundMonomerFraction,	"BoundMonomerFraction");
	pTSD->SetValue(5, m_FilamentTotal,			"FilamentTotal");
	pTSD->SetValue(6, m_MeanFilamentSize,		"MeanFilamentSize");
	pTSD->SetValue(7, m_SDevFilamentSize,		"SDevFilamentSize");
	pTSD->SetValue(8, m_MeanFilamentLength,		"MeanFilamentLength");
	pTSD->SetValue(9, m_SDevFilamentLength,		"SDevFilamentLength");

	m_pState->AddTimeSeriesData(pTSD);
}

// Function to check that the user-specified data is valid and. As this process
// is internally generated by the shadow SimBox we do not perform validity checking.

bool prFormin::ValidateData(const CInputData &riData)
{
	return false;
}

// Function to check that the data for a process that is internally generated
// is valid, and to create the xxProcessState to serialise the data to file.

bool prFormin::InternalValidateData(const ISimState* const pISimState)
{
	// An xxProcessState is created to hold the data that the process wants
	// to write to file. Data is passed as a series of CTimeSeriesData objects
	// as used for CHistoryState. Because this function is called after the
	// original xxProcess instance is copied (so that the xxProcessObject instance
	// can be discarded), creating the xxAggregateState here does not result in
	// it being destroyed. Hence, we can write the XML opening tags to the file safely.

	// The process state's file name depends on whether it is XML-enabled or not,
	// so we use two different SetState() signatures to allow for this. If it
	// is XML-enabled, we write out the standard processing instructions and
	// wrapper tags <ProcessState></ProcessState> as the first and last elements 
	// in the file. Because the process state can write data until the simulation 
	// ends, we only write the end tag in the base class's destructor.

#if EnableXMLProcesses == SimXMLEnabled

    SetState(new xxProcessState(xxBase::GetPSPrefix() + GetProcessType() + ToString(GetId()) + "." + pISimState->GetRunId() + ".xml", GetStartTime(), GetEndTime(), pISimState->GetRunId(), GetProcessType()));

	// Note that the opening <Header> tag is written in the xxProcessState class
	// but the closing tag is written here. This is a hack.

	zOutStream& os = m_pState->putXMLStartTags();
//	os << "<MonomerTotal>"		<< m_MonomerTotal		<< "</MonomerTotal>"	<< zEndl;
	os << "</Header>" << zEndl;

#elif EnableXMLProcesses == SimXMLDisabled

	SetState(new xxProcessState(xxBase::GetPSPrefix() + GetProcessType() + ToString(GetId()) + "." + pISimState->GetRunId(), GetStartTime(), GetEndTime(), pISimState->GetRunId(), GetProcessType()));

//	zOutStream& os = m_pState->putASCIIStartTags();
//	os << "    MonomerTotal		" << m_MonomerTotal	 << zEndl;

#endif

	return true;
}

// Function used by the associated ACN to connect itself to the process so that
// it can serialise its data to file.

void prFormin::SetACN(const aeForminNetwork* pACN)
{
	m_pACN = pACN;
}

// ****************************************
// Forwarding functions to the base class' implementation of IModifyProcess interface

bool prFormin::IsModifiable() const
{
	return InternalIsModifiable();
}

void prFormin::SetModifiable(const xxCommand* const pCommand)
{
	return InternalSetModifiable(pCommand);
}

void prFormin::SetUnmodifiable(const xxCommand* const pCommand)
{
	return InternalSetUnmodifiable(pCommand);
}

// Function to allow the process to prevent any further modifications to itself.
// Note that a warning is logged if this command is sent more than once to the
// same process.

void prFormin::SetIrreversibleUnmodifiable(const xxCommand* const pCommand)
{	
	return InternalSetIrreversibleUnmodifiable(pCommand);
}

// ****************************************
// Implementation of IModifyFormin interface

void prFormin::SetCondenseDelay(const xxCommand* const pCommand)
{
	const pcBLMVesicleFusionSetCondenseDelay* const pCmd = dynamic_cast<const pcBLMVesicleFusionSetCondenseDelay*>(pCommand);

	const zString pid = pCmd->GetPid();
	const long  delay = pCmd->GetDelay();
	
	if(pid == GetPid() && IsModifiable() && delay >= 0)
	{
		m_CondenseDelay = delay;

		std::cout << "setting condense delay to " << delay << zEndl;

		new CLogpcBLMVesicleFusionSetCondenseDelay(pCmd->GetExecutionTime(), pid, delay);

	}
	else
	{
		new CLogCommandFailed(pCmd->GetExecutionTime(), pCmd);
	}
}



